# Generated by Django 5.2.7 on 2025-10-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
